-- phpMyAdmin SQL Dump
-- version 4.7.7
-- https://www.phpmyadmin.net/
--
-- Servidor: mysql-luis:3306
-- Tiempo de generación: 11-02-2018 a las 03:26:40
-- Versión del servidor: 5.7.20
-- Versión de PHP: 7.1.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `inf-scroll-php`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `bposts`
--

CREATE TABLE `bposts` (
  `id` int(11) NOT NULL,
  `content` text NOT NULL,
  `date` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `bposts`
--

INSERT INTO `bposts` (`id`, `content`, `date`) VALUES
(1, '', 1518318028),
(2, '', 1518318028),
(3, '', 1518318029),
(4, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Obsecro, inquit, Torquate, haec dicit Epicurus? At modo dixeras nihil in istis rebus esse, quod interesset. Quodsi ipsam honestatem undique pertectam atque absolutam. Duo Reges: constructio interrete. </p>\n\n<p>Perge porro; Quid me istud rogas? Quid enim possumus hoc agere divinius? Haec dicuntur inconstantissime. Pugnant Stoici cum Peripateticis. Rationis enim perfectio est virtus; </p>\n\n<p>Facete M. Haec dicuntur inconstantissime. Peccata paria. Istam voluptatem perpetuam quis potest praestare sapienti? Et non ex maxima parte de tota iudicabis? </p>\n\n', 1518318030),
(5, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Haeret in salebra. Hic ambiguo ludimur. Avaritiamne minuis? Est, ut dicis, inquit; Duo Reges: constructio interrete. Nunc haec primum fortasse audientis servire debemus. </p>\n\n<p>Si id dicis, vicimus. Eam stabilem appellas. Primum divisit ineleganter; Quid enim? Quid ad utilitatem tantae pecuniae? Esse enim, nisi eris, non potes. </p>\n\n<p>Si id dicis, vicimus. Sed tamen intellego quid velit. Quae diligentissime contra Aristonem dicuntur a Chryippo. Scrupulum, inquam, abeunti; Sed ad bona praeterita redeamus. Frater et T. </p>\n\n', 1518318031),
(6, '', 1518318032),
(7, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Philosophi autem in suis lectulis plerumque moriuntur. Efficiens dici potest. In schola desinis. Illi enim inter se dissentiunt. Duo Reges: constructio interrete. Neutrum vero, inquit ille. Quod autem ratione actum est, id officium appellamus. Sed nunc, quod agimus; Sed fac ista esse non inportuna; </p>\n\n<p>Haec dicuntur inconstantissime. Ea possunt paria non esse. </p>\n\n<p>Omnis enim est natura diligens sui. Summum enÃ­m bonum exposuit vacuitatem doloris; Quamquam tu hanc copiosiorem etiam soles dicere. Erit enim mecum, si tecum erit. </p>\n\n', 1518318033),
(8, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Honesta oratio, Socratica, Platonis etiam. Beatus sibi videtur esse moriens. Duarum enim vitarum nobis erunt instituta capienda. Teneo, inquit, finem illi videri nihil dolere. Duo Reges: constructio interrete. Sed ille, ut dixi, vitiose. Quod cum dixissent, ille contra. </p>\n\n<p>Sit enim idem caecus, debilis. Maximus dolor, inquit, brevis est. Nemo nostrum istius generis asotos iucunde putat vivere. Primum divisit ineleganter; </p>\n\n<p>Quo modo autem philosophus loquitur? Ecce aliud simile dissimile. Cur tantas regiones barbarorum pedibus obiit, tot maria transmisit? Quid nunc honeste dicit? Sedulo, inquam, faciam. Facete M. </p>\n\n', 1518318034),
(9, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Bestiarum vero nullum iudicium puto. Sed ad illum redeo. Atqui reperies, inquit, in hoc quidem pertinacem; Quare ad ea primum, si videtur; Quid iudicant sensus? </p>\n\n<p>Duo Reges: constructio interrete. Contineo me ab exemplis. Quid ad utilitatem tantae pecuniae? Sed hoc sane concedamus. </p>\n\n<p>Hoc non est positum in nostra actione. A mene tu? Beatum, inquit. A mene tu? Eiuro, inquit adridens, iniquum, hac quidem de re; Hoc simile tandem est? </p>\n\n', 1518318035),
(10, '', 1518318036),
(11, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ille incendat? Numquam facies. </p>\n\n<p>Atqui reperies, inquit, in hoc quidem pertinacem; Sed plane dicit quod intellegit. Ratio quidem vestra sic cogit. Hunc vos beatum; Aperiendum est igitur, quid sit voluptas; Quodsi ipsam honestatem undique pertectam atque absolutam. </p>\n\n<p>Quis hoc dicit? Sed nunc, quod agimus; An tu me de L. Contemnit enim disserendi elegantiam, confuse loquitur. Non est ista, inquam, Piso, magna dissensio. Duo Reges: constructio interrete. Que Manilium, ab iisque M. Neutrum vero, inquit ille. </p>\n\n', 1518318037),
(12, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quantum Aristoxeni ingenium consumptum videmus in musicis? Nihil opus est exemplis hoc facere longius. Duo Reges: constructio interrete. Beatus sibi videtur esse moriens. </p>\n\n<p>Itaque hic ipse iam pridem est reiectus; Explanetur igitur. Summum enÃ­m bonum exposuit vacuitatem doloris; Gloriosa ostentatio in constituendo summo bono. Quia nec honesto quic quam honestius nec turpi turpius. </p>\n\n<p>Neutrum vero, inquit ille. Si verbum sequimur, primum longius verbum praepositum quam bonum. Audeo dicere, inquit. Illi enim inter se dissentiunt. Honesta oratio, Socratica, Platonis etiam. </p>\n\n', 1518318038),
(13, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nummus in Croesi divitiis obscuratur, pars est tamen divitiarum. Hic ambiguo ludimur. Duo Reges: constructio interrete. Videmus igitur ut conquiescere ne infantes quidem possint. </p>\n\n<p>Urgent tamen et nihil remittunt. Aliter enim explicari, quod quaeritur, non potest. Esse enim quam vellet iniquus iustus poterat inpune. Solum praeterea formosum, solum liberum, solum civem, stultost; </p>\n\n<p>Sint ista Graecorum; Frater et T. </p>\n\n', 1518318039),
(14, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quod totum contra est. Tum mihi Piso: Quid ergo? Is es profecto tu. Nam Pyrrho, Aristo, Erillus iam diu abiecti. Eadem nunc mea adversum te oratio est. Efficiens dici potest. Duo Reges: constructio interrete. </p>\n\n<p>Scio enim esse quosdam, qui quavis lingua philosophari possint; Quare attende, quaeso. Sed eum qui audiebant, quoad poterant, defendebant sententiam suam. </p>\n\n<p>In schola desinis. Id est enim, de quo quaerimus. Quae quidem vel cum periculo est quaerenda vobis; Ita credo. </p>\n\n', 1518318040),
(15, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Certe non potest. Quam ob rem tandem, inquit, non satisfacit? Obsecro, inquit, Torquate, haec dicit Epicurus? Sed quod proximum fuit non vidit. Bonum integritas corporis: misera debilitas. Duo Reges: constructio interrete. Est, ut dicis, inquit; Contemnit enim disserendi elegantiam, confuse loquitur. </p>\n\n<p>Nos cum te, M. Disserendi artem nullam habuit. Consequentia exquirere, quoad sit id, quod volumus, effectum. Ut optime, secundum naturam affectum esse possit. At ille pellit, qui permulcet sensum voluptate. Quid sequatur, quid repugnet, vident. </p>\n\n<p>Quod ea non occurrentia fingunt, vincunt Aristonem; Sed ille, ut dixi, vitiose. Ipse Epicurus fortasse redderet, ut Sextus Peducaeus, Sex. At, si voluptas esset bonum, desideraret. </p>\n\n', 1518318041),
(16, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eadem nunc mea adversum te oratio est. Pugnant Stoici cum Peripateticis. Qui est in parvis malis. Quid de Platone aut de Democrito loquar? Mihi, inquam, qui te id ipsum rogavi? </p>\n\n<p>Summus dolor plures dies manere non potest? Videsne quam sit magna dissensio? Rationis enim perfectio est virtus; Non igitur bene. Ut optime, secundum naturam affectum esse possit. Cyrenaici quidem non recusant; </p>\n\n<p>Duo Reges: constructio interrete. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Sint ista Graecorum; Illi enim inter se dissentiunt. Quis non odit sordidos, vanos, leves, futtiles? Quare attende, quaeso. </p>\n\n', 1518318042),
(17, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Apud ceteros autem philosophos, qui quaesivit aliquid, tacet; Summum a vobis bonum voluptas dicitur. Cur id non ita fit? Iam in altera philosophiae parte. Sed haec in pueris; Duo Reges: constructio interrete. </p>\n\n<p>Aufert enim sensus actionemque tollit omnem. Tuo vero id quidem, inquam, arbitratu. Quippe: habes enim a rhetoribus; Sed residamus, inquit, si placet. Egone quaeris, inquit, quid sentiam? </p>\n\n<p>Istam voluptatem perpetuam quis potest praestare sapienti? Ille incendat? Et nemo nimium beatus est; Quid sequatur, quid repugnet, vident. At multis se probavit. </p>\n\n', 1518318043),
(18, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. At miser, si in flagitiosa et vitiosa vita afflueret voluptatibus. Quid de Platone aut de Democrito loquar? Quis est tam dissimile homini. Hanc quoque iucunditatem, si vis, transfer in animum; </p>\n\n<p>Sed residamus, inquit, si placet. Ea possunt paria non esse. Certe, nisi voluptatem tanti aestimaretis. Vestri haec verecundius, illi fortasse constantius. Si longus, levis dictata sunt. Vide, quantum, inquam, fallare, Torquate. Non quam nostram quidem, inquit Pomponius iocans; </p>\n\n<p>Quid, si etiam iucunda memoria est praeteritorum malorum? Quid enim possumus hoc agere divinius? Duo Reges: constructio interrete. Tum Quintus: Est plane, Piso, ut dicis, inquit. Utilitatis causa amicitia est quaesita. </p>\n\n', 1518318044),
(19, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Si longus, levis; Certe non potest. </p>\n\n<p>Duo Reges: constructio interrete. Cum praesertim illa perdiscere ludus esset. Graece donan, Latine voluptatem vocant. Immo alio genere; Nihil enim hoc differt. Sequitur disserendi ratio cognitioque naturae; </p>\n\n<p>Tanta vis admonitionis inest in locis; Nihil ad rem! Ne sit sane; Vitiosum est enim in dividendo partem in genere numerare. Collatio igitur ista te nihil iuvat. </p>\n\n', 1518318045),
(20, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Et non ex maxima parte de tota iudicabis? Summum a vobis bonum voluptas dicitur. </p>\n\n<p>Recte, inquit, intellegis. Nunc omni virtuti vitium contrario nomine opponitur. Deinde dolorem quem maximum? Sed nimis multa. At multis malis affectus. </p>\n\n<p>Indicant pueri, in quibus ut in speculis natura cernitur. Quid de Pythagora? Si longus, levis. Bonum liberi: misera orbitas. Duo Reges: constructio interrete. Quo modo autem philosophus loquitur? Non semper, inquam; </p>\n\n', 1518318046),
(21, '', 1518318046),
(22, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Hanc ergo intuens debet institutum illud quasi signum absolvere. Praeteritis, inquit, gaudeo. Hic nihil fuit, quod quaereremus. Audeo dicere, inquit. Duo Reges: constructio interrete. Paria sunt igitur. Quid, de quo nulla dissensio est? </p>\n\n<p>Quid sequatur, quid repugnet, vident. Ita nemo beato beatior. Quis est tam dissimile homini. Idemne, quod iucunde? </p>\n\n<p>At ille pellit, qui permulcet sensum voluptate. Sic enim censent, oportunitatis esse beate vivere. Tria genera bonorum; </p>\n\n', 1518318052),
(23, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Optime, inquam. Falli igitur possumus. Honesta oratio, Socratica, Platonis etiam. Et quidem, inquit, vehementer errat; Cum praesertim illa perdiscere ludus esset. Addidisti ad extremum etiam indoctum fuisse. </p>\n\n<p>Duo Reges: constructio interrete. Si quae forte-possumus. Ego vero isti, inquam, permitto. An potest cupiditas finiri? Tuo vero id quidem, inquam, arbitratu. Oratio me istius philosophi non offendit; Quae cum essent dicta, discessimus. </p>\n\n<p>Sed tu istuc dixti bene Latine, parum plane. Inde igitur, inquit, ordiendum est. Efficiens dici potest. Quare attende, quaeso. Quis Aristidem non mortuum diligit? Equidem etiam Epicurum, in physicis quidem, Democriteum puto. </p>\n\n', 1518318053),
(24, '', 1518318054),
(25, '', 1518318055),
(26, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nosti, credo, illud: Nemo pius est, qui pietatem-; At enim hic etiam dolore. </p>\n\n<p>Duo Reges: constructio interrete. Quamquam haec quidem praeposita recte et reiecta dicere licebit. Praeteritis, inquit, gaudeo. Facete M. </p>\n\n<p>Poterat autem inpune; Quae autem natura suae primae institutionis oblita est? </p>\n\n', 1518318056),
(27, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duo Reges: constructio interrete. Ita credo. </p>\n\n<p>Invidiosum nomen est, infame, suspectum. Quis enim redargueret? Non est igitur voluptas bonum. Bonum incolumis acies: misera caecitas. Nunc omni virtuti vitium contrario nomine opponitur. Suo genere perveniant ad extremum; </p>\n\n<p>Quae contraria sunt his, malane? Nihilo magis. Est enim effectrix multarum et magnarum voluptatum. Quamquam te quidem video minime esse deterritum. Videamus animi partes, quarum est conspectus illustrior; </p>\n\n', 1518318057),
(28, '', 1518318058),
(29, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nescio quo modo praetervolavit oratio. Ita relinquet duas, de quibus etiam atque etiam consideret. Praeclare hoc quidem. Duo Reges: constructio interrete. Si quae forte-possumus. Ut id aliis narrare gestiant? </p>\n\n<p>De illis, cum volemus. Erat enim res aperta. Non autem hoc: igitur ne illud quidem. Haec para/doca illi, nos admirabilia dicamus. Tamen a proposito, inquam, aberramus. Traditur, inquit, ab Epicuro ratio neglegendi doloris. </p>\n\n<p>Nosti, credo, illud: Nemo pius est, qui pietatem-; Eam stabilem appellas. Quodsi ipsam honestatem undique pertectam atque absolutam. Multoque hoc melius nos veriusque quam Stoici. Bonum patria: miserum exilium. Hoc Hieronymus summum bonum esse dixit. Quid iudicant sensus? </p>\n\n', 1518318058),
(30, '', 1518318059),
(31, '', 1518318060),
(32, '', 1518318061),
(33, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid Zeno? Tum mihi Piso: Quid ergo? Illi enim inter se dissentiunt. Comprehensum, quod cognitum non habet? Idemne, quod iucunde? Graccho, eius fere, aequalÃ­? Nihil enim iam habes, quod ad corpus referas; Duo Reges: constructio interrete. </p>\n\n<p>Quonam, inquit, modo? Summae mihi videtur inscitiae. </p>\n\n<p>Nihil illinc huc pervenit. Aperiendum est igitur, quid sit voluptas; Torquatus, is qui consul cum Cn. Facete M. Si quicquam extra virtutem habeatur in bonis. Nam ista vestra: Si gravis, brevis; </p>\n\n', 1518318062),
(34, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid ad utilitatem tantae pecuniae? Quos quidem tibi studiose et diligenter tractandos magnopere censeo. Magna laus. Ita graviter et severe voluptatem secrevit a bono. Nunc de hominis summo bono quaeritur; </p>\n\n<p>Pauca mutat vel plura sane; Frater et T. Honesta oratio, Socratica, Platonis etiam. Sic enim censent, oportunitatis esse beate vivere. Sed nimis multa. </p>\n\n<p>Haeret in salebra. Duo Reges: constructio interrete. </p>\n\n', 1518318063),
(35, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Istam voluptatem, inquit, Epicurus ignorat? Utram tandem linguam nescio? Hoc sic expositum dissimile est superiori. Velut ego nunc moveor. Avaritiamne minuis? Egone quaeris, inquit, quid sentiam? </p>\n\n<p>Duo Reges: constructio interrete. Dicimus aliquem hilare vivere; </p>\n\n<p>Etenim semper illud extra est, quod arte comprehenditur. Sint modo partes vitae beatae. Conferam tecum, quam cuique verso rem subicias; Tanta vis admonitionis inest in locis; Sed tamen intellego quid velit. </p>\n\n', 1518318064),
(36, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Hoc est non dividere, sed frangere. Memini me adesse P. Beatus sibi videtur esse moriens. Duo Reges: constructio interrete. </p>\n\n<p>Minime vero, inquit ille, consentit. Negat enim summo bono afferre incrementum diem. Sed in rebus apertissimis nimium longi sumus. </p>\n\n<p>Ita ne hoc quidem modo paria peccata sunt. Pugnant Stoici cum Peripateticis. Summum enÃ­m bonum exposuit vacuitatem doloris; Si quicquam extra virtutem habeatur in bonis. Comprehensum, quod cognitum non habet? Ratio quidem vestra sic cogit. </p>\n\n', 1518318065),
(37, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ego in hoc resisto; Fortemne possumus dicere eundem illum Torquatum? Age sane, inquam. </p>\n\n<p>At iam decimum annum in spelunca iacet. Duo Reges: constructio interrete. Quod vestri non item. Sed residamus, inquit, si placet. Si quicquam extra virtutem habeatur in bonis. At hoc in eo M. </p>\n\n<p>Negare non possum. Utilitatis causa amicitia est quaesita. Tenent mordicus. An tu me de L. </p>\n\n', 1518318066),
(38, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid iudicant sensus? Si quae forte-possumus. Quamquam tu hanc copiosiorem etiam soles dicere. Eiuro, inquit adridens, iniquum, hac quidem de re; Duo Reges: constructio interrete. Non igitur bene. Philosophi autem in suis lectulis plerumque moriuntur. </p>\n\n<p>Recte, inquit, intellegis. Vitae autem degendae ratio maxime quidem illis placuit quieta. Atqui reperies, inquit, in hoc quidem pertinacem; Traditur, inquit, ab Epicuro ratio neglegendi doloris. </p>\n\n<p>Audeo dicere, inquit. Ille incendat? Putabam equidem satis, inquit, me dixisse. Quo plebiscito decreta a senatu est consuli quaestio Cn. Quid enim est a Chrysippo praetermissum in Stoicis? Quare conare, quaeso. </p>\n\n', 1518318067),
(39, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. De vacuitate doloris eadem sententia erit. Haec dicuntur inconstantissime. Nihilo beatiorem esse Metellum quam Regulum. Eadem nunc mea adversum te oratio est. Duo Reges: constructio interrete. </p>\n\n<p>Praeteritis, inquit, gaudeo. Ubi ut eam caperet aut quando? Non risu potius quam oratione eiciendum? Neutrum vero, inquit ille. Quo tandem modo? </p>\n\n<p>Conferam tecum, quam cuique verso rem subicias; Stoicos roga. </p>\n\n', 1518318068),
(40, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proclivi currit oratio. Itaque ab his ordiamur. Nos cum te, M. Iam id ipsum absurdum, maximum malum neglegi. </p>\n\n<p>Graccho, eius fere, aequalÃ­? Tria genera bonorum; An potest cupiditas finiri? Aliter autem vobis placet. Memini me adesse P. </p>\n\n<p>Ergo id est convenienter naturae vivere, a natura discedere. Est, ut dicis, inquam. Duo Reges: constructio interrete. Sed plane dicit quod intellegit. Prodest, inquit, mihi eo esse animo. Ait enim se, si uratur, Quam hoc suave! dicturum. </p>\n\n', 1518318069),
(41, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Illa tamen simplicia, vestra versuta. Nam si amitti vita beata potest, beata esse non potest. Duo Reges: constructio interrete. Tria genera bonorum; Quid est enim aliud esse versutum? </p>\n\n<p>Hunc vos beatum; Stoici scilicet. Polycratem Samium felicem appellabant. Idem iste, inquam, de voluptate quid sentit? Bonum valitudo: miser morbus. Consequens enim est et post oritur, ut dixi. Eaedem res maneant alio modo. </p>\n\n<p>A mene tu? Videsne quam sit magna dissensio? Nihilo magis. Tanta vis admonitionis inest in locis; Certe, nisi voluptatem tanti aestimaretis. Et ille ridens: Video, inquit, quid agas; </p>\n\n', 1518318070),
(42, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Illa tamen simplicia, vestra versuta. Polycratem Samium felicem appellabant. Non autem hoc: igitur ne illud quidem. Eadem nunc mea adversum te oratio est. Duo Reges: constructio interrete. </p>\n\n<p>Traditur, inquit, ab Epicuro ratio neglegendi doloris. Eadem nunc mea adversum te oratio est. Quamquam te quidem video minime esse deterritum. Putabam equidem satis, inquit, me dixisse. Deprehensus omnem poenam contemnet. </p>\n\n<p>Summum enÃ­m bonum exposuit vacuitatem doloris; Nam ista vestra: Si gravis, brevis; Hanc quoque iucunditatem, si vis, transfer in animum; Tubulo putas dicere? Rhetorice igitur, inquam, nos mavis quam dialectice disputare? Sed tamen intellego quid velit. </p>\n\n', 1518318071),
(43, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quod cum dixissent, ille contra. De hominibus dici non necesse est. Deinde dolorem quem maximum? De illis, cum volemus. Haeret in salebra. Quid est igitur, inquit, quod requiras? </p>\n\n<p>Beatus autem esse in maximarum rerum timore nemo potest. Tanta vis admonitionis inest in locis; Duo Reges: constructio interrete. Hoc enim identidem dicitis, non intellegere nos quam dicatis voluptatem. Suo genere perveniant ad extremum; Velut ego nunc moveor. Hunc vos beatum; </p>\n\n<p>Nunc haec primum fortasse audientis servire debemus. Quod autem satis est, eo quicquid accessit, nimium est; Nihil enim iam habes, quod ad corpus referas; At ille pellit, qui permulcet sensum voluptate. Non risu potius quam oratione eiciendum? Quonam, inquit, modo? Pauca mutat vel plura sane; </p>\n\n', 1518318072),
(44, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Beatus sibi videtur esse moriens. Neutrum vero, inquit ille. Et ille ridens: Video, inquit, quid agas; Istam voluptatem perpetuam quis potest praestare sapienti? Quis enim redargueret? Eaedem res maneant alio modo. </p>\n\n<p>Duo Reges: constructio interrete. Tuo vero id quidem, inquam, arbitratu. Quis Aristidem non mortuum diligit? Quid enim possumus hoc agere divinius? Illi enim inter se dissentiunt. </p>\n\n<p>Cave putes quicquam esse verius. Summum enÃ­m bonum exposuit vacuitatem doloris; Quod ea non occurrentia fingunt, vincunt Aristonem; Refert tamen, quo modo. Bestiarum vero nullum iudicium puto. Quam ob rem tandem, inquit, non satisfacit? Restinguet citius, si ardentem acceperit. An tu me de L. </p>\n\n', 1518318073),
(45, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed haec omittamus; Sed ea mala virtuti magnitudine obruebantur. Facile est hoc cernere in primis puerorum aetatulis. Quis est tam dissimile homini. </p>\n\n<p>Duo Reges: constructio interrete. Nobis aliter videtur, recte secusne, postea; Quid de Platone aut de Democrito loquar? Videamus animi partes, quarum est conspectus illustrior; Sed fac ista esse non inportuna; Sed haec omittamus; Quam ob rem tandem, inquit, non satisfacit? Quid sequatur, quid repugnet, vident. </p>\n\n<p>Memini vero, inquam; Sed vos squalidius, illorum vides quam niteat oratio. Restinguet citius, si ardentem acceperit. Tanta vis admonitionis inest in locis; Invidiosum nomen est, infame, suspectum. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Eadem nunc mea adversum te oratio est. </p>\n\n', 1518318074),
(46, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Hos contra singulos dici est melius. Et ille ridens: Video, inquit, quid agas; Iam contemni non poteris. </p>\n\n<p>Illud non continuo, ut aeque incontentae. Duo Reges: constructio interrete. Velut ego nunc moveor. Efficiens dici potest. Inde igitur, inquit, ordiendum est. Occultum facinus esse potuerit, gaudebit; </p>\n\n<p>Putabam equidem satis, inquit, me dixisse. Quid igitur, inquit, eos responsuros putas? Quae cum essent dicta, discessimus. Qui est in parvis malis. Quae cum dixisset paulumque institisset, Quid est? Recte dicis; </p>\n\n', 1518318075),
(47, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Facile est hoc cernere in primis puerorum aetatulis. Quid de Pythagora? Hic ambiguo ludimur. Cur deinde Metrodori liberos commendas? Eam stabilem appellas. Quae ista amicitia est? </p>\n\n<p>Nihil sane. Duo Reges: constructio interrete. </p>\n\n<p>Quam si explicavisset, non tam haesitaret. Quid iudicant sensus? Tubulo putas dicere? </p>\n\n', 1518318076),
(48, '', 1518318076),
(49, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum praesertim illa perdiscere ludus esset. Collatio igitur ista te nihil iuvat. Duo Reges: constructio interrete. Cum audissem Antiochum, Brute, ut solebam, cum M. Estne, quaeso, inquam, sitienti in bibendo voluptas? Quid de Platone aut de Democrito loquar? </p>\n\n<p>Qui ita affectus, beatum esse numquam probabis; Quam nemo umquam voluptatem appellavit, appellat; Quid me istud rogas? Hoc loco tenere se Triarius non potuit. </p>\n\n<p>Quid igitur, inquit, eos responsuros putas? Estne, quaeso, inquam, sitienti in bibendo voluptas? Quamquam te quidem video minime esse deterritum. Quid autem habent admirationis, cum prope accesseris? Hic nihil fuit, quod quaereremus. </p>\n\n', 1518318077),
(50, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tenent mordicus. Ita nemo beato beatior. Quae sequuntur igitur? Quae quidem vel cum periculo est quaerenda vobis; Duo Reges: constructio interrete. </p>\n\n<p>Quid ergo? Bonum negas esse divitias, praeposÃ¬tum esse dicis? Que Manilium, ab iisque M. Quis istum dolorem timet? Sed mehercule pergrata mihi oratio tua. Si longus, levis. </p>\n\n<p>Quid vero? Vitiosum est enim in dividendo partem in genere numerare. </p>\n\n', 1518318078);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `bposts`
--
ALTER TABLE `bposts`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `bposts`
--
ALTER TABLE `bposts`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
